In [114]:
import requests
import json
import pandas as pd
import time

In [144]:
def daily_df(ticker):

    API_URL = "https://www.alphavantage.co/query"

    data = {
        "function": "TIME_SERIES_DAILY",
        "symbol": ticker,
        "outputsize": "compact",
        "datatype": "json",
        "apikey": "PVGTC9P6IUS7XLQ9",
        }

    response = requests.get(API_URL, params=data)

    if response.status_code == 200:
        stock_data = response.json()
        # print(stock_data)
        meta_data = stock_data['Meta Data']
        daily_data = stock_data['Time Series (Daily)']
        daily_dataframe_rev = pd.DataFrame.from_dict(daily_data)
        daily_dataframe = daily_dataframe_rev.transpose()     
        daily_dataframe.columns = ['open', 'high', 'low', 'close', 'volume']
        
        return daily_dataframe

In [145]:
daily_df('AAPL').head()

                open      high       low     close    volume
2019-10-25  243.1600  246.7200  242.8900  246.5800  15827692
2019-10-24  244.5100  244.8000  241.8100  243.5800  17318800
2019-10-23  242.1000  243.2400  241.2200  243.1800  18957200
2019-10-22  241.1600  242.2000  239.6200  239.9600  20573400
2019-10-21  237.5200  240.9900  237.3200  240.5100  21811800

In [139]:
def alltickers():
    data = pd.read_csv("/Users/rohitgarudadri/Desktop/Rohit/Programming/YHack/ticker_picker/constituents_csv.csv", usecols=['Symbol'])
    t = time.time()
    print(t)

    for i in range (5):
        print(i)
        daily_df(data.iloc[i][0]).head()
        
    # for i in range (5):
    #     print(i)
    #     daily_df(data.iloc[i][0]).head()
    t = time.time()
    print(t)

In [141]:
alltickers()

1572064538.475061
0

KeyError: 'Meta Data'

In [105]:
daily_df('ATVI').head()

               open     high      low    close   volume
2019-10-25  56.2100  56.2500  55.0200  55.2600  5428080
2019-10-24  55.1800  55.7400  54.6200  55.4400  5649100
2019-10-23  54.5600  55.3300  54.3500  54.8000  3341000
2019-10-22  55.6700  55.7200  54.4900  54.5200  4353500
2019-10-21  55.2500  55.8200  54.7300  55.5100  5925300